//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestNuxiba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleados
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<decimal> Sueldo { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
    
        public virtual usuarios usuarios { get; set; }
    }
}
