//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestNuxiba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_usuarios
    {
        public string Login { get; set; }
        public string Nombre { get; set; }
        public string Paterno { get; set; }
        public string Materno { get; set; }
        public Nullable<decimal> Sueldo { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public int userid { get; set; }
    }
}
